language: java
jdk:
- openjdk7
script:
 - chmod a+x .travis/push
after_script:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'master' ]]; then .travis/push production || exit $?; fi
notifications:
  email: true